# SPACE QUESTIONS - 20 per level
SPACE_QUESTIONS = {
    1: [
        ("What is the closest star to Earth?", ["Moon", "Sun", "Mars", "Venus", "Polaris"], 1, "This star provides light and heat to our planet"),
        ("How many planets are in our solar system?", ["7", "8", "9", "10", "12"], 1, "Pluto was reclassified, leaving this many planets"),
        ("What is a galaxy?", ["A planet", "Collection of stars and solar systems", "A moon", "A comet", "An asteroid"], 1, "The Milky Way is an example of this vast structure"),
        ("What is the Moon?", ["A planet", "Earth's natural satellite", "A star", "A comet", "An asteroid"], 1, "This celestial body orbits Earth and affects tides"),
        ("Which planet is known as the Red Planet?", ["Venus", "Jupiter", "Mars", "Saturn", "Mercury"], 2, "Its reddish appearance comes from iron oxide on surface"),
        ("What is a comet?", ["A planet", "Icy body that develops tail near Sun", "A star", "A moon", "A galaxy"], 1, "These icy objects develop glowing tails when near the Sun"),
        ("Which planet is largest in our solar system?", ["Earth", "Saturn", "Jupiter", "Neptune", "Uranus"], 2, "This gas giant has a giant red spot storm"),
        ("What causes day and night on Earth?", ["Earth orbiting Sun", "Earth's rotation", "Moon's orbit", "Sun's movement", "Tides"], 1, "Earth spins on its axis causing this cycle"),
        ("What is a constellation?", ["Single star", "Pattern of stars", "Planet group", "Galaxy type", "Comet trail"], 1, "The Big Dipper is part of one of these star patterns"),
        ("How long does Earth take to orbit the Sun?", ["24 hours", "30 days", "365 days", "12 months exactly", "400 days"], 2, "This period defines one year"),
        ("What is an asteroid?", ["Ice ball", "Rocky object orbiting Sun", "Gas cloud", "Star fragment", "Planet core"], 1, "Most of these rocky objects orbit in a belt between Mars and Jupiter"),
        ("Which planet has rings?", ["Mars", "Earth", "Venus", "Saturn", "Mercury"], 3, "This planet is famous for its beautiful ring system"),
        ("What is a meteor?", ["Planet", "Space rock entering atmosphere", "Star", "Moon", "Galaxy"], 1, "Commonly called a shooting star when it burns up in atmosphere"),
        ("What is the Milky Way?", ["A candy bar", "Our galaxy", "A planet", "A constellation", "A nebula"], 1, "Our solar system is located in this spiral galaxy"),
        ("Which planet is closest to the Sun?", ["Venus", "Mercury", "Earth", "Mars", "Jupiter"], 1, "This small, cratered planet has extreme temperature variations"),
        ("What is gravity?", ["Light", "Force pulling objects together", "Heat", "Magnetism", "Wind"], 1, "This force keeps planets orbiting the Sun"),
        ("What is a light-year?", ["One year", "Distance light travels in a year", "Time measurement", "Speed of light", "Earth's orbit"], 1, "Used to measure vast distances in space"),
        ("What causes the seasons on Earth?", ["Distance from Sun", "Earth's tilted axis", "Moon phases", "Solar flares", "Rotation speed"], 1, "Earth's 23.5-degree tilt causes this annual cycle"),
        ("What is the ISS?", ["A planet", "International Space Station", "A telescope", "A satellite", "A rocket"], 1, "Orbiting laboratory where astronauts live and work"),
        ("How many moons does Earth have?", ["None", "One", "Two", "Three", "Four"], 1, "Earth has this many natural satellites"),
    ],
    2: [
        ("What is a black hole?", ["Empty space", "Region with extreme gravity", "Dark planet", "Space tunnel", "Asteroid"], 1, "Nothing, not even light, can escape from this object"),
        ("What is the asteroid belt?", ["Planet ring", "Region of asteroids between Mars and Jupiter", "Comet trail", "Moon orbit", "Galaxy edge"], 1, "Region containing millions of rocky objects between two planets"),
        ("What is a supernova?", ["New star", "Exploding star", "Planet collision", "Comet impact", "Galaxy merger"], 1, "Massive stellar explosion that can outshine entire galaxies"),
        ("What is the Kuiper Belt?", ["Asteroid belt", "Region beyond Neptune with icy objects", "Saturn's rings", "Galaxy arm", "Comet source near Jupiter"], 1, "Region beyond Neptune containing Pluto and other icy bodies"),
        ("What causes eclipses?", ["Earth's rotation", "Moon blocking Sun or Earth's shadow on Moon", "Solar flares", "Planet alignment", "Comet passing"], 1, "Occurs when one celestial body blocks light from another"),
        ("What is the Great Red Spot?", ["Mars feature", "Giant storm on Jupiter", "Sun spot", "Nebula", "Galaxy center"], 1, "Massive storm on Jupiter that's been raging for centuries"),
        ("What is a nebula?", ["Dead star", "Cloud of gas and dust in space", "Galaxy type", "Planet atmosphere", "Comet tail"], 1, "Star-forming regions often called stellar nurseries"),
        ("What is escape velocity?", ["Orbital speed", "Speed needed to leave planet's gravity", "Light speed", "Rotation rate", "Maximum velocity"], 1, "Minimum speed needed to break free from gravitational pull"),
        ("What are Saturn's rings made of?", ["Gas", "Ice and rock particles", "Liquid", "Plasma", "Dust only"], 1, "Billions of particles ranging from tiny grains to house-sized chunks"),
        ("What is the habitable zone?", ["Earth's surface", "Region where liquid water can exist", "Inside atmosphere", "Near Sun", "Galaxy center"], 1, "Goldilocks zone where temperatures allow liquid water"),
        ("What is a pulsar?", ["Pulsing planet", "Rapidly rotating neutron star", "Variable star", "Orbiting asteroid", "Binary system"], 1, "Rapidly spinning neutron star emitting beams of radiation"),
        ("What is the cosmic microwave background?", ["Star light", "Radiation from Big Bang", "Galaxy glow", "Sun's heat", "Black hole emission"], 1, "Afterglow of the Big Bang detected throughout universe"),
        ("What is a white dwarf?", ["Young star", "Dead star remnant", "Planet type", "Asteroid", "Comet core"], 1, "Dense remnant left after a medium-sized star dies"),
        ("What is redshift?", ["Star color", "Light stretched by expansion", "Mars appearance", "Sunset color", "Heat signature"], 1, "Lengthening of wavelengths due to objects moving away"),
        ("What causes solar flares?", ["Sunspots", "Magnetic field disruptions", "Planet alignment", "Asteroid impacts", "Nuclear fusion"], 1, "Sudden releases of magnetic energy on the Sun's surface"),
        ("What is the Oort Cloud?", ["Visible cloud", "Theoretical sphere of comets around solar system", "Galaxy cluster", "Nebula type", "Asteroid group"], 1, "Theoretical spherical shell of icy objects at edge of solar system"),
        ("What is orbital period?", ["Rotation time", "Time to complete one orbit", "Year length", "Day length", "Eclipse cycle"], 1, "Time taken for celestial body to complete one revolution"),
        ("What are Van Allen Belts?", ["Asteroid belt", "Radiation zones around Earth", "Saturn's rings", "Galaxy arms", "Comet trails"], 1, "Zones of charged particles trapped by Earth's magnetic field"),
        ("What is a binary star system?", ["Double planet", "Two stars orbiting each other", "Twin galaxies", "Paired moons", "Split asteroid"], 1, "System where two stars orbit their common center of mass"),
        ("What is the solar wind?", ["Sun's rotation", "Stream of charged particles from Sun", "Space breeze", "Planet atmospheres", "Comet tails"], 1, "Continuous flow of charged particles released from Sun's corona"),
    ],
    3: [
        ("What is dark matter?", ["Black holes", "Invisible matter detected by gravity", "Empty space", "Dark energy", "Antimatter"], 1, "Makes up 85% of matter but doesn't interact with light"),
        ("What is the Schwarzschild radius?", ["Planet size", "Black hole event horizon", "Star diameter", "Galaxy radius", "Orbit distance"], 1, "Radius of the event horizon of a non-rotating black hole"),
        ("What is gravitational lensing?", ["Telescope", "Bending of light by gravity", "Planet alignment", "Lens-shaped galaxy", "Optical illusion"], 1, "Massive objects bend spacetime, deflecting light paths"),
        ("What is stellar nucleosynthesis?", ["Star birth", "Element creation in stars", "Star death", "Planet formation", "Fusion process"], 1, "Process by which stars create heavier elements from lighter ones"),
        ("What is the Chandrasekhar limit?", ["Speed limit", "Maximum mass for white dwarf", "Black hole size", "Galaxy size", "Star brightness"], 1, "About 1.4 solar masses - beyond this, white dwarf collapses"),
        ("What is the Roche limit?", ["Distance limit", "Distance where tidal forces tear object apart", "Speed limit", "Size limit", "Temperature limit"], 1, "Distance where tidal forces overcome object's self-gravity"),
        ("What causes pulsars to pulse?", ["Brightness variation", "Rotation of beam emission", "Orbit period", "Expansion-contraction", "Magnetic reversals"], 1, "Lighthouse effect as neutron star rotates and beam sweeps past Earth"),
        ("What is the Drake equation?", ["Orbit formula", "Equation estimating alien civilizations", "Gravity equation", "Light travel formula", "Expansion rate"], 1, "Probabilistic argument estimating number of detectable alien civilizations"),
        ("What is Hawking radiation?", ["Solar radiation", "Theoretical black hole emission", "Cosmic rays", "Star light", "Pulsar beams"], 1, "Theoretical radiation emitted by black holes due to quantum effects"),
        ("What is a magnetar?", ["Magnetic planet", "Neutron star with extreme magnetic field", "Pulsar type", "Asteroid", "Galaxy core"], 1, "Neutron star with extremely powerful magnetic field"),
        ("What is the Eddington limit?", ["Speed limit", "Maximum luminosity before radiation pressure wins", "Size limit", "Temperature limit", "Distance limit"], 1, "Point where radiation pressure balances gravitational attraction"),
        ("What is cosmic inflation?", ["Universe expansion", "Rapid expansion after Big Bang", "Star formation", "Galaxy growth", "Black hole growth"], 1, "Exponential expansion of space in first fraction of second after Big Bang"),
        ("What is the main sequence?", ["Star order", "Stage where stars fuse hydrogen", "Galaxy type", "Planet lineup", "Constellation"], 1, "Longest phase of stellar life, fusing hydrogen to helium in core"),
        ("What is the CNO cycle?", ["Star birth", "Stellar fusion process using carbon catalyst", "Planet formation", "Comet orbit", "Galaxy rotation"], 1, "Catalytic cycle using carbon, nitrogen, oxygen to fuse hydrogen"),
        ("What is a Lagrange point?", ["Star center", "Point where gravitational forces balance", "Galaxy edge", "Orbit position", "Asteroid location"], 1, "Positions where gravitational forces of two bodies balance with centrifugal force"),
        ("What is the Hertzsprung-Russell diagram?", ["Star map", "Plot of stellar luminosity vs temperature", "Galaxy chart", "Constellation guide", "Planet positions"], 1, "Fundamental diagram plotting star brightness against temperature"),
        ("What is frame dragging?", ["Picture effect", "Spacetime twisted by rotating mass", "Orbit decay", "Tidal effect", "Light bending"], 1, "Rotating massive objects drag spacetime around them"),
        ("What is quasar?", ["Quiet star", "Extremely luminous active galactic nucleus", "Pulsar type", "Planet type", "Asteroid"], 1, "Extremely bright and distant active galactic nucleus powered by black hole"),
        ("What is Population III stars?", ["Common stars", "First generation stars", "Old stars", "Planet orbiting stars", "Binary stars"], 1, "Hypothetical first generation of stars made only of hydrogen and helium"),
        ("What is Baryonic acoustic oscillations?", ["Sound in space", "Density fluctuations from early universe", "Star vibrations", "Planet atmospheres", "Galaxy waves"], 1, "Regular periodic fluctuations in density of visible matter in universe"),
    ],
    4: [
        ("What is the Tolman-Oppenheimer-Volkoff limit?", ["Speed limit", "Maximum mass for neutron star", "Black hole size", "White dwarf limit", "Star brightness"], 1, "Maximum mass (~2-3 solar masses) before neutron star collapses to black hole"),
        ("What is the cosmic distance ladder?", ["Space elevator", "Series of methods to measure distances", "Asteroid belt", "Galaxy structure", "Star classification"], 1, "Succession of methods to determine astronomical distances"),
        ("What is Olbers' paradox?", ["Time paradox", "Why night sky is dark", "Twin paradox", "Information paradox", "Expansion paradox"], 1, "Question of why night sky is dark if universe is infinite and eternal"),
        ("What is the Jeans instability?", ["Orbital instability", "Condition for gravitational collapse", "Star wobble", "Planet migration", "Asteroid collision"], 1, "Condition for cloud of gas to collapse under its own gravity"),
        ("What is synchrotron radiation?", ["Solar radiation", "Radiation from charged particles in magnetic fields", "Thermal emission", "Nuclear decay", "Chemical light"], 1, "Electromagnetic radiation from relativistic charged particles in magnetic fields"),
        ("What is the Fermi paradox?", ["Time travel", "Contradiction between probability and lack of evidence for aliens", "Quantum paradox", "Relativity paradox", "Observation paradox"], 1, "Contradiction between high probability of alien life and lack of contact"),
        ("What is the cosmological constant?", ["Star number", "Dark energy density", "Expansion rate", "Light speed", "Gravity constant"], 1, "Einstein's term representing dark energy driving accelerated expansion"),
        ("What is the flatness problem?", ["Geometry issue", "Why universe curvature is so close to flat", "Galaxy shape", "Orbit problem", "Expansion issue"], 1, "Question of why universe density is so precisely at critical value"),
        ("What is primordial nucleosynthesis?", ["First stars", "Element formation in early universe", "Planet formation", "Life origins", "Galaxy formation"], 1, "Creation of light elements in first minutes after Big Bang"),
        ("What is the horizon problem?", ["Distance limit", "Why distant regions have same temperature", "Black hole boundary", "Observable universe edge", "Galaxy limit"], 1, "Question of why causally disconnected regions have same properties"),
        ("What is the Sunyaev-Zel'dovich effect?", ["Star wobble", "CMB distortion by galaxy clusters", "Gravitational lens", "Redshift variation", "Cosmic expansion"], 1, "Distortion of CMB by scattering off hot gas in galaxy clusters"),
        ("What is asymptotic giant branch?", ["Galaxy arm", "Late stellar evolution phase", "Black hole region", "Nebula edge", "Comet path"], 1, "Late phase of stellar evolution for low-to-medium mass stars"),
        ("What is the Great Attractor?", ["Black hole", "Gravitational anomaly pulling galaxies", "Galaxy cluster", "Dark matter region", "Cosmic void"], 1, "Gravitational anomaly in space toward which galaxies are flowing"),
        ("What is the Sachs-Wolfe effect?", ["Optical illusion", "CMB anisotropy from gravitational redshift", "Galaxy rotation", "Star formation", "Black hole lensing"], 1, "CMB temperature variations due to gravitational potential wells"),
        ("What is metallicity in astronomy?", ["Iron content", "Abundance of elements heavier than helium", "Metal planets", "Asteroid composition", "Core material"], 1, "Proportion of matter made up of chemical elements other than hydrogen and helium"),
        ("What is the Lyman-alpha forest?", ["Star cluster", "Series of absorption lines in quasar spectra", "Galaxy group", "Nebula type", "Cosmic structure"], 1, "Series of absorption lines due to hydrogen clouds along line of sight"),
        ("What is gravitational time dilation?", ["Clock error", "Time slowing in strong gravity", "Orbital period change", "Star aging", "Universe expansion"], 1, "Time passes more slowly in stronger gravitational fields"),
        ("What is the cosmic web?", ["Spider nebula", "Large-scale structure of universe", "Galaxy spiral", "Star network", "Asteroid belt"], 1, "Foam-like structure of filaments and voids on largest scales"),
        ("What is the Zel'dovich approximation?", ["Galaxy estimate", "Model for structure formation", "Distance calculation", "Mass estimate", "Age determination"], 1, "Approximation for evolution of density perturbations in early universe"),
        ("What is the virial theorem?", ["Energy law", "Relationship between kinetic and potential energy", "Orbit law", "Momentum conservation", "Force balance"], 1, "For stable system, twice kinetic energy equals minus potential energy"),
    ],
    5: [
        ("What is the ekpyrotic universe model?", ["Expanding model", "Cyclic model from colliding branes", "Steady state", "Oscillating model", "Multiverse theory"], 1, "Cosmological model where Big Bang results from collision of branes"),
        ("What is the MOND hypothesis?", ["Dark matter", "Modified Newtonian Dynamics", "Quantum gravity", "String theory", "Inflation theory"], 1, "Alternative to dark matter modifying Newton's laws at low accelerations"),
        ("What is the conformal cyclic cosmology?", ["Eternal inflation", "Penrose's cyclic universe model", "Big bounce", "Steady state", "Multiverse"], 1, "Roger Penrose's model where universe undergoes infinite cycles"),
        ("What is the Unruh effect?", ["Black hole radiation", "Accelerating observer sees thermal bath", "Gravitational waves", "Quantum entanglement", "Cosmic expansion"], 1, "Accelerating observer perceives vacuum as warm thermal bath of particles"),
        ("What is the holographic principle?", ["3D projection", "Information on volume encoded on boundary", "Optical illusion", "Galaxy imaging", "Black hole shadow"], 1, "Theory that volume of space encoded on lower-dimensional boundary"),
        ("What is loop quantum gravity?", ["String theory", "Quantization of spacetime", "Dark energy theory", "Inflation model", "Multiverse theory"], 1, "Attempt to merge quantum mechanics and general relativity"),
        ("What is the information paradox?", ["Data loss", "Black hole information problem", "Measurement paradox", "Quantum paradox", "Entropy issue"], 1, "Problem of information seemingly destroyed by black holes"),
        ("What is baryogenesis?", ["Star formation", "Creation of matter-antimatter asymmetry", "Planet formation", "Galaxy formation", "Element creation"], 1, "Physical process explaining why universe has more matter than antimatter"),
        ("What is cosmic censorship conjecture?", ["Universe privacy", "Singularities hidden by event horizons", "Information hiding", "Dark matter", "Black hole theorem"], 1, "Hypothesis that singularities are always hidden behind event horizons"),
        ("What is the no-hair theorem?", ["Black hole simplicity", "Black holes characterized by three parameters only", "Entropy law", "Information theorem", "Singularity property"], 1, "Black holes completely characterized by mass, charge, and angular momentum"),
        ("What is the Bekenstein bound?", ["Size limit", "Maximum entropy in bounded region", "Black hole limit", "Information limit", "Energy bound"], 1, "Maximum amount of information contained within finite region of space"),
        ("What is the firewall paradox?", ["Solar phenomenon", "Black hole information problem", "Stellar collision", "Gamma ray burst", "Quasar emission"], 1, "Proposed solution to information paradox suggesting firewalls at horizons"),
        ("What is the weak gravity conjecture?", ["Gravity measurement", "Constraint on quantum gravity theories", "Force hierarchy", "Dark energy property", "Inflation condition"], 1, "States gravity must be weakest force in any consistent quantum gravity theory"),
        ("What is the landscape problem in string theory?", ["Terrain issue", "Vast number of vacuum solutions", "Multiverse topology", "Dimension count", "Symmetry breaking"], 1, "String theory allows ~10^500 possible vacuum configurations"),
        ("What is asymptotic safety in gravity?", ["Distance limit", "Quantum gravity at high energies", "Black hole stability", "Expansion behavior", "Singularity avoidance"], 1, "Scenario where gravity remains well-defined at arbitrarily high energies"),
        ("What is the measure problem in cosmology?", ["Distance measurement", "Probability in infinite multiverse", "Scale definition", "Time measurement", "Density calculation"], 1, "Problem of defining probabilities in eternally inflating multiverse"),
        ("What is spontaneous scalarization?", ["Field generation", "Neutron star developing scalar field", "Vacuum fluctuation", "Phase transition", "Symmetry breaking"], 1, "Phenomenon where neutron stars spontaneously develop scalar fields"),
        ("What is the trans-Planckian problem?", ["Length issue", "Modes smaller than Planck length during inflation", "Energy limit", "Time scale", "Mass bound"], 1, "Problem that inflation involves modes with wavelengths below Planck scale"),
        ("What is the swampland conjectures?", ["Dark matter", "Constraints on effective field theories", "Black hole properties", "Inflation conditions", "Symmetry restrictions"], 1, "Set of conjectures constraining which effective field theories come from string theory"),
        ("What is the cosmological bootstrap?", ["Early universe", "Constraints from consistency and symmetries", "Inflation mechanism", "Structure formation", "Expansion history"], 1, "Approach to constrain cosmological correlators using symmetries and consistency"),
    ]
}
